### PR TITLE
Remove icon from tray message.

### PR DESCRIPTION
**Pull request by tokejepsen**
This PR will restore backwards compatibility with PyQt 5.8.

### CODE REVIEW

**Comment by tokejepsen** [comment]
This is a fix for #5

**Comment by BigRoy** [comment]
Sweet! Are we still able to set the icon using this?

**Comment by tokejepsen** [comment]
> Are we still able to set the icon using this?

On the message?
No, the difference between 5.9 and 5.8 methods are passing of the icon.

**Comment by BigRoy** [comment]
Ah, thought this was changing the icon in the tray but is only about the initial launch popup. Great! :)

**Pull request merged**
